basket/urls.py
from django.urls import path
# from .views import login, register, logout, profile


app_name = 'basket'
urlpatterns = [
    # path('login/', login, name='login'),
    # path('register/', register, name='register'),
    # path('logout/', logout, name='logout'),
    # path('profile/', profile, name='profile'),
]

baskets/urls.py
from django.urls import path
from .views import basket_remove, basket_edit, basket_add #, BasketAddCreateView

app_name = 'baskets'
urlpatterns = [
    path('add/<int:product_id>/', basket_add, name='basket_add'),
    # path('add/<int:product_id>/', BasketAddCreateView.as_view(), name='basket_add'),
    path('remove/<int:product_id>/', basket_remove, name='basket_remove'),
    # path('remove/<int:product_id>/', BasketDeleteView.as_view(), name='basket_remove'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from mainapp.views import IndexTemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexTemplateView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import Logout, LoginListView, RegisterListView, ProfileFormView, verify

app_name = 'users'
urlpatterns = [
    path('login/', LoginListView.as_view(), name='login'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('profile/', ProfileFormView.as_view(), name='profile'),

    path('verify/<str:email>/<str:activation_key>', verify, name='verify'),
]

baskets/models.py
from django.db import models
from users.models import User
from mainapp.models import Product
# Create your models here.


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity

    # @staticmethod
    def total_quantity(self):
        baskets = Basket.objects.filter(user=self.user)
        total_quantity = 0
        for basket in baskets:
            total_quantity += basket.quantity
        return total_quantity

    # @staticmethod
    def total_sum(self):
        baskets = Basket.objects.filter(user=self.user)
        total_sum = 0
        for basket in baskets:
            total_sum += basket.sum()
        return total_sum

baskets/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404

from django.shortcuts import HttpResponseRedirect
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView

from geekshop.mixin import BaseClassContextMixin
from mainapp.models import Product
from baskets.models import Basket
# Create your views here.


# class BasketAddCreateView(CreateView):
#     model = Basket
#
#     def get(self, request, *args, **kwargs):
#         user_select = request.user
#         product = Product.objects.get(id=kwargs['product_id'])
#         baskets = Basket.objects.filter(user=user_select, product=product)
#         if not baskets.exists():
#             Basket.objects.create(user=user_select, product=product, quantity=1)
#         else:
#             basket = baskets.first()
#             basket.quantity += 1
#             basket.save()
#         return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
#
#     @method_decorator(user_passes_test(lambda u: u.is_authenticated))
#     def dispatch(self, request, *args, **kwargs):
#         return super().dispatch(request, *args, **kwargs)


@login_required
def basket_add(request, product_id):
    user_select = request.user
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=user_select, product=product)
    if not baskets.exists():
        Basket.objects.create(user=user_select, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, product_id):
    Basket.objects.get(id=product_id).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_edit(request, id, quantity):
    if request.is_ajax():
        basket = Basket.objects.get(id=id)
        if quantity > 0:
            basket.quantity = quantity
            basket.save()
        else:
            basket.delete()

        baskets = Basket.objects.filter(user=request.user)

        context = {
            'baskets': baskets
        }

        result = render_to_string('baskets/baskets.html', context)
        return JsonResponse({'result': result})

baskets/templates/baskets/baskets.html
{% load method %}

<div class="basket_list">
    {% if baskets %}
        {% for basket in baskets %}
            {% if forloop.first %}
                <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
{#                    Корзина <span class="badge badge-secondary badge-pill">{{ variable|total_quantity:user }}</span>#}
                    Корзина <span class="badge badge-secondary badge-pill">{{ basket.total_quantity }}</span>
                </h4>
            {% endif %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product }}</h5>
                    <p class="card-text">{{ basket.product.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="{{ basket.id }}" type="number" class="form-control"
                                       value="{{ basket.quantity }}" min="0">
                            </div>
                            <div class="col-lg-4">{{ basket.sum }} руб.</div>
                            <div class="col-lg-4">
                                <a href="{% url 'baskets:basket_remove' basket.id %}">Del
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            {% if forloop.last %}
                <div class="card mb-3">
                    <div class="card-footer">
                        <p class="float-left">Итого</p>
{#                        <h4 class="float-right">{{ variable|total_sum:user }} руб.</h4>#}
                        <h4 class="float-right">{{ basket.total_sum }} руб.</h4>
                    </div>
                </div>
                <button type="button" class="btn btn-success btn-lg float-right">Оформить</button>
            {% endif %}
        {% endfor %}
    {% else %}
        <h4 class="mt-3 mb-3 text-center">Корзина пуста</h4>
    {% endif %}
</div>