baskets/urls.py
from django.urls import path
from .views import basket_remove, basket_edit, basket_add #, BasketAddCreateView

app_name = 'baskets'
urlpatterns = [
    path('add/<int:product_id>/', basket_add, name='basket_add'),
    # path('add/<int:product_id>/', BasketAddCreateView.as_view(), name='basket_add'),
    path('remove/<int:product_id>/', basket_remove, name='basket_remove'),
    # path('remove/<int:product_id>/', BasketDeleteView.as_view(), name='basket_remove'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from mainapp.views import IndexTemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexTemplateView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from .views import ProductsListView

app_name = 'mainapp'
urlpatterns = [
    # path('', products, name='index'),
    path('', ProductsListView.as_view(), name='index'),
    # path('category/<int:category_id>/', products, name='category'),
    path('category/<int:category_id>/', ProductsListView.as_view(), name='category'),
    # path('page/<int:page_id>/', products, name='page'),
    # path('page/<int:page_id>/', ProductsListView.as_view(), name='page'),
]

users/urls.py
from django.urls import path
from .views import Logout, LoginListView, RegisterListView, ProfileFormView, verify

app_name = 'users'
urlpatterns = [
    path('login/', LoginListView.as_view(), name='login'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('profile/', ProfileFormView.as_view(), name='profile'),

    path('verify/<str:email>/<str:activation_key>', verify, name='verify'),
]

mainapp/models.py
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='product_images', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} | {self.category.name}'

mainapp/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.views.generic import TemplateView, ListView

from geekshop.mixin import BaseClassContextMixin
from mainapp.models import ProductCategory, Product


# Create your views here.


class IndexTemplateView(TemplateView, BaseClassContextMixin):
    title = 'geekshop | main page'
    template_name = 'mainapp/index.html'


class ProductsListView(ListView, BaseClassContextMixin):
    model = Product
    paginate_by = 3
    title = 'geekshop | products'
    template_name = 'mainapp/products.html'
    context_object_name = 'products'

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()

        if kwargs.get('category_id'):
            self.object_list = self.object_list.filter(category_id=kwargs['category_id'])

        context = self.get_context_data()
        return self.render_to_response(context)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ProductCategory.objects.all().order_by('id')

        return context



# def index(request):
#     return render(request, 'mainapp/index.html', {'title': 'geekshop | main page'})


# def products(request, category_id=None, page_id=1):
#
#     products = Product.objects.filter(category_id=category_id).order_by('id') if category_id != None else Product.objects.all().order_by('id')
#
#     paginator = Paginator(products, per_page=3)
#
#     try:
#         products_paginator = paginator.page(page_id)
#     except PageNotAnInteger:
#         products_paginator = paginator.page(1)
#     except EmptyPage:
#         products_paginator = paginator.page(paginator.num_pages)
#
#     context = {'title': 'geekshop | products',
#                'categories': ProductCategory.objects.all().order_by('id'),
#                'products': products_paginator}
#     return render(request, 'mainapp/products.html', context)
#

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title|title }}</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    {% block css %}
    {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'mainapp:index' %}">Каталог <i class="fas fa-shopping-bag"></i></a>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' %}">{{ user }}
                            <i class="fas fa-user-circle"></i></a>
                    </li>
                    {% if user.username == 'admin' %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admins:index' %}">
                                <i class="fas fa-users-cog"></i></a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static '/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static '/vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>
<script src="{% static '/js/baskets.js' %}"></script>
</body>

</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block css %}
    <link href="{% static '/css/index.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">GeekShop Store</h1>
                <p>
                    Новые образы и лучшие бренды на GeekShop Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{%  url 'mainapp:index' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block css %}
    <link href="{% static '/css/products.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    <a href="{% url 'mainapp:category' 0 %}"
                       class="list-group-item">Все категории</a>
                    {% for category in categories %}
                        <a href="{% url 'mainapp:category' category.id %}"
                           class="list-group-item">{{ category.name }}</a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <!-- carousel -->
                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <!-- products -->
                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top"
                                         src="{{ product.image.url }}"
                                         alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="#">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price }} руб.</h5>
                                    <p class="card-text">{{ product.description }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a href="{% url 'baskets:basket_add' product.id %}" class="btn btn-outline-success">Отправить
                                        в корзину</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        {#                        <li class="page-item {% if not products.has_previous %} disabled {% endif %}">#}
                        {#                            <a class="page-link"#}
                        {#                               href="{% if products.has_previous %} {% url 'mainapp:page' products.previous_page_number %} {% else %} # {% endif %}"#}
                        {#                               tabindex="-1" aria-disabled="true">Previous</a>#}
                        {#                        </li>#}
                        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }} {% else %} # {% endif %}"
                               tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                        {#                        {% for page in products.paginator.page_range %}#}
                        {% for page in page_obj.paginator.page_range %}
                            <li class="page-item"><a class="page-link"
                                                     href="?page={{ page }}">{{ page }}</a></li>
                        {% endfor %}
                        {#                        <li class="page-item {% if not products.has_next %} disabled {% endif %}">#}
                        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                            {#                            <a class="page-link"#}
                            {#                               href="{% if products.has_next %} {% url 'mainapp:page' products.next_page_number %} {% else %} # {% endif %}"#}
                            {#                               tabindex="-1" aria-disabled="true">Next</a>#}
                            <a class="page-link"
                               href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }} {% else %} # {% endif %}"
                               tabindex="-1" aria-disabled="true">Next</a>
                        </li>
                    </ul>
                </nav>

            </div>

        </div>

    </div>
    <!-- /.container -->
{% endblock %}


{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}